---
title: "claseac"
author: "clase"
date: "24 de marzo de 2017"
output: html_document
---
```{r}
library(metodosMultivariados2017)
library(datasets)
library(knitr)
```

```{r}
tea<-tea[-1]
tea$Años<-as.factor(tea$Años)
summary
Z<-dichotom(tea)
teab<-burt(tea)
head(teab)
```
```{r}

```

```{r}
#data("HairEyeColor")
tbl <- apply(teab, c(1,2), sum)
dimnames(tbl) <- list(dimnames(tbl)[[1]],
                      dimnames(tbl)[[2]])
kable(tbl)
```

```{r}
X <- contingency_dummies(tbl)[[1]]
Y <- contingency_dummies(tbl)[[2]]
```

```{r}
kable(head(X))
```

```{r}
kable(tail(Y))
```

```{r}
kable(t(X) %*% Y)
```

```{r}
kable(t(X) %*% X)
```

```{r}
kable(t(Y) %*% Y)
```

```{r}
kable(t(X) %*% Y / sum(as.numeric(t(X) %*% Y)))
```

```{r}
ones_row <- rep(1, ncol(X))
ones_col <- rep(1, ncol(Y))
N <- as.numeric(ones_row %*% t(X) %*% Y %*% ones_col)
P <- t(X) %*% Y / N
kable(P)
```

```{r}
# (X'X)^(-1)X'Y
Pr <- solve(t(X) %*% X, t(X) %*% Y)
kable(Pr)
```

```{r}
library(ggtern)
plot_dat <- data.frame(Pr, check.names = FALSE)
ggtern(plot_dat, aes(x = `Género.Hombre`,
               y = `Años.4`,
               z = `Ingreso.Bajo`,
                colour = `Años.1`)) +
  geom_point() + 
  geom_text(aes(label = row.names(plot_dat)))
```

```{r}
chi_dist <-  function(row1, row2, tbl) {
  col_masses <-  as.numeric(apply(tbl, 2, sum)) / 
    sum(as.numeric(tbl))
  Pr <- solve(t(X) %*% X, t(X) %*% Y)
  dif <- as.numeric(Pr[row1, ]) - as.numeric(Pr[row2, ])
  sqrt(sum((1 / col_masses)*dif^2))
}
```

```{r}
col_mass <- apply(tbl, 2, sum) / 
  sum(as.numeric(tbl))
#kable(col_mass)
```

```{r}
chi_dist(1, 2, tbl)
chi_dist(1, 4, tbl)
```

```{r}
hair_types <- dimnames(tbl)[[1]]
n_types <- length(hair_types) 
row_dist_mat <- matrix(0, 
                       ncol = n_types, 
                       nrow = n_types,
                       dimnames = list(hair_types, hair_types))
for (i in 1:(n_types - 1)) {
  for (j in i:n_types) {
    row_dist_mat[i, j] <- chi_dist(i, j, tbl)
    row_dist_mat[j, i] <-  row_dist_mat[i, j]
  }
}
kable(row_dist_mat)
```

```{r}
col_mass <- apply(tbl, 2, sum) / 
  sum(as.numeric(tbl))
#kable(col_mass)
```

```{r}
# restar a cada columna su masa (el porcentaje obsevado de ese color de ojos)
Pr_tilde <- Pr - ones_col %*% t(col_mass)
kable(Pr_tilde)
```

```{r}
kable(ones_col %*% t(col_mass))

```

```{r}
apply(tbl, 2, sum) / sum(as.numeric(tbl))
```

```{r}
n <- sum(as.numeric(tbl))
P <- tbl/n
row_mass <- as.numeric(apply(P, 1, sum)) 
col_mass <- as.numeric(apply(P, 2, sum)) 
Dr <- diag(row_mass) 
Dc <- diag(col_mass)
RowProfile <- solve(Dr, P) 
RowProfileC <- RowProfile
for (i in 1:nrow(RowProfile)) 
  RowProfileC[i, ] <- RowProfileC[i, ] -col_mass
covR <- RowProfileC %*% solve(Dc) %*% t(RowProfileC)
res <- eigen(covR)
row_factor1 <- res$vectors[ ,1] * sqrt(res$values[1])
row_factor2 <- res$vectors[ ,2] * sqrt(res$values[2])
row_names <- dimnames(tbl)[[1]]

```

```{r}
data <- data.frame(row_factor1, 
                   row_factor2,
                   row_names)
ggplot(data, aes(x = row_factor1, y= row_factor2, colour = row_names)) +
  geom_point(size = 2, alpha = 0.6) +
  geom_text(aes(x = row_factor1, y= row_factor2, label = row_names))


```

```{r}
# varianza explicada
var_exp <- cumsum(res$values) / sum(res$values)
scales::percent(var_exp)
```

```{r}
ColProfile <- P %*% solve(Dc) 
ColProfileC <- ColProfile
for (j in 1:ncol(ColProfileC)) 
  ColProfileC[ ,j] <- ColProfileC[ ,j] - row_mass
covC <- t(ColProfileC) %*% solve(Dr) %*% ColProfileC
res <- eigen(covC)
col_factor1 <- res$vectors[ ,1] * sqrt(res$values[1])
col_factor2 <- res$vectors[ ,2] * sqrt(res$values[2])
col_names <- dimnames(tbl)[[2]]
```

```{r}
data <- data.frame(col_factor1, 
                   col_factor2,
                   col_names)
ggplot(data, aes(x = col_factor1, y= col_factor2, colour = col_names)) +
  geom_point(size = 2, alpha = 0.6) +
  geom_text(aes(x = col_factor1, y= col_factor2, label = col_names))
```

```{r}
data_row <- data.frame(factor1 = row_factor1, 
                   factor2 = row_factor2,
                   variable = row_names, type = "hair")
data_col <- data.frame(factor1 = - col_factor1, 
                   factor2 = col_factor2,
                   variable = col_names, type = "eyes")
data_all <- rbind(data_row, data_col)

ggplot(data_all, aes(x = factor1, y= factor2, colour = variable, shape = type)) +
  geom_point(size = 2, alpha = 0.6) +
  geom_text(aes(x = factor1, y= factor2, label = variable))
```

```{r}

```

